   
services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - .:/workspaces/{{ cookiecutter.project_name }}:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ./docker/config/postgres_defaults.env
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy

  #############################################################################
  #
  # PostgreSQL container for local experimentation
  #
  # Settings:
  # - Latest official PostgreSQL image
  # - Data persistence using local volume
  # - The postgres password is injected using Docker secret
  # - Health check 
  #
  #############################################################################
  postgres:
    build:
      context: .
      dockerfile: docker/postgresql.Dockerfile
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    env_file:
      - ./docker/config/pgadmin_defaults.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider localhost:8080 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - postgres

volumes:
  postgres_data: 
    driver: local

secrets:
  postgres_password:
    file: ./docker/config/secrets/postgres_password
